"""
Visualize the diverse shapes generated by data_utils.py
"""
import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
from data_utils import generate_shape_pair_v2

jax.config.update("jax_enable_x64", True)

def main():
    n = 64
    L = jnp.pi
    
    # Generate 8 sample pairs to show diversity
    fig, axes = plt.subplots(4, 4, figsize=(12, 12))
    fig.suptitle("Diverse Shape Pairs (Init → Target)", fontsize=14)
    
    for i in range(8):
        key = jax.random.PRNGKey(i * 42 + 7)
        rho_init, rho_target = generate_shape_pair_v2(key, n=n, L=L)
        
        row = i // 2
        col = (i % 2) * 2
        
        axes[row, col].imshow(rho_init, origin='lower', cmap='viridis')
        axes[row, col].set_title(f'Init {i+1}')
        axes[row, col].axis('off')
        
        axes[row, col+1].imshow(rho_target, origin='lower', cmap='magma')
        axes[row, col+1].set_title(f'Target {i+1}')
        axes[row, col+1].axis('off')

    plt.tight_layout()
    plt.savefig('shape_samples_v2.png', dpi=150)
    print('Saved shape_samples_v2.png')

if __name__ == "__main__":
    main()

